package entity

type ReceiveOrderBase struct {
	CommonResult
	Data []ReceiveOrderBaseData
}

type ReceiveOrderBaseData struct {
	ReceiveOrderBusinessOfficeName                    string `json:"receive_order_business_office_name"`
	ReceiveOrderBusinessOfficeStopID                  string `json:"receive_order_business_office_stop_id"`
	ReceiveOrderBusinessOfficeStopName                string `json:"receive_order_business_office_stop_name"`
	ReceiveOrderCancelDate                            string `json:"receive_order_cancel_date"`
	ReceiveOrderCancelTypeID                          string `json:"receive_order_cancel_type_id"`
	ReceiveOrderCancelTypeName                        string `json:"receive_order_cancel_type_name"`
	ReceiveOrderChargeAmount                          string `json:"receive_order_charge_amount"`
	ReceiveOrderConfirmCheckID                        string `json:"receive_order_confirm_check_id"`
	ReceiveOrderConfirmCheckName                      string `json:"receive_order_confirm_check_name"`
	ReceiveOrderConfirmIds                            string `json:"receive_order_confirm_ids"`
	ReceiveOrderConsigneeAddress1                     string `json:"receive_order_consignee_address1"`
	ReceiveOrderConsigneeAddress2                     string `json:"receive_order_consignee_address2"`
	ReceiveOrderConsigneeFax                          string `json:"receive_order_consignee_fax"`
	ReceiveOrderConsigneeKana                         string `json:"receive_order_consignee_kana"`
	ReceiveOrderConsigneeName                         string `json:"receive_order_consignee_name"`
	ReceiveOrderConsigneeTel                          string `json:"receive_order_consignee_tel"`
	ReceiveOrderConsigneeZipCode                      string `json:"receive_order_consignee_zip_code"`
	ReceiveOrderCopyFromOrderID                       string `json:"receive_order_copy_from_order_id"`
	ReceiveOrderCreationDate                          string `json:"receive_order_creation_date"`
	ReceiveOrderCreatorID                             string `json:"receive_order_creator_id"`
	ReceiveOrderCreatorName                           string `json:"receive_order_creator_name"`
	ReceiveOrderCreditApprovalAmount                  string `json:"receive_order_credit_approval_amount"`
	ReceiveOrderCreditApprovalDate                    string `json:"receive_order_credit_approval_date"`
	ReceiveOrderCreditApprovalFaxPrintingDate         string `json:"receive_order_credit_approval_fax_printing_date"`
	ReceiveOrderCreditApprovalNo                      string `json:"receive_order_credit_approval_no"`
	ReceiveOrderCreditApprovalRate                    string `json:"receive_order_credit_approval_rate"`
	ReceiveOrderCreditApprovalTypeID                  string `json:"receive_order_credit_approval_type_id"`
	ReceiveOrderCreditApprovalTypeName                string `json:"receive_order_credit_approval_type_name"`
	ReceiveOrderCreditAuthorizationCenterID           string `json:"receive_order_credit_authorization_center_id"`
	ReceiveOrderCreditAuthorizationCenterName         string `json:"receive_order_credit_authorization_center_name"`
	ReceiveOrderCreditNumberPayments                  string `json:"receive_order_credit_number_payments"`
	ReceiveOrderCreditTypeID                          string `json:"receive_order_credit_type_id"`
	ReceiveOrderCreditTypeName                        string `json:"receive_order_credit_type_name"`
	ReceiveOrderCustomerID                            string `json:"receive_order_customer_id"`
	ReceiveOrderCustomerTypeID                        string `json:"receive_order_customer_type_id"`
	ReceiveOrderCustomerTypeName                      string `json:"receive_order_customer_type_name"`
	ReceiveOrderDate                                  string `json:"receive_order_date"`
	ReceiveOrderDeletedFlag                           string `json:"receive_order_deleted_flag"`
	ReceiveOrderDeliveryCutFormID                     string `json:"receive_order_delivery_cut_form_id"`
	ReceiveOrderDeliveryCutFormNote                   string `json:"receive_order_delivery_cut_form_note"`
	ReceiveOrderDeliveryFeeAmount                     string `json:"receive_order_delivery_fee_amount"`
	ReceiveOrderDeliveryID                            string `json:"receive_order_delivery_id"`
	ReceiveOrderDeliveryMethodID                      string `json:"receive_order_delivery_method_id"`
	ReceiveOrderDeliveryMethodName                    string `json:"receive_order_delivery_method_name"`
	ReceiveOrderDeliveryName                          string `json:"receive_order_delivery_name"`
	ReceiveOrderDepositAmount                         string `json:"receive_order_deposit_amount"`
	ReceiveOrderDepositDate                           string `json:"receive_order_deposit_date"`
	ReceiveOrderDepositTypeID                         string `json:"receive_order_deposit_type_id"`
	ReceiveOrderDepositTypeName                       string `json:"receive_order_deposit_type_name"`
	ReceiveOrderDivideFromOrderID                     string `json:"receive_order_divide_from_order_id"`
	ReceiveOrderGiftFlag                              string `json:"receive_order_gift_flag"`
	ReceiveOrderGoodsAmount                           string `json:"receive_order_goods_amount"`
	ReceiveOrderGruopingTag                           string `json:"receive_order_gruoping_tag"`
	ReceiveOrderHopeDeliveryDate                      string `json:"receive_order_hope_delivery_date"`
	ReceiveOrderHopeDeliveryTimeSlotID                string `json:"receive_order_hope_delivery_time_slot_id"`
	ReceiveOrderHopeDeliveryTimeSlotName              string `json:"receive_order_hope_delivery_time_slot_name"`
	ReceiveOrderID                                    string `json:"receive_order_id"`
	ReceiveOrderImportDate                            string `json:"receive_order_import_date"`
	ReceiveOrderImportTypeID                          string `json:"receive_order_import_type_id"`
	ReceiveOrderImportTypeName                        string `json:"receive_order_import_type_name"`
	ReceiveOrderImportantCheckID                      string `json:"receive_order_important_check_id"`
	ReceiveOrderImportantCheckName                    string `json:"receive_order_important_check_name"`
	ReceiveOrderImportantCheckPicID                   string `json:"receive_order_important_check_pic_id"`
	ReceiveOrderImportantCheckPicName                 string `json:"receive_order_important_check_pic_name"`
	ReceiveOrderIncludePossibleOrderID                string `json:"receive_order_include_possible_order_id"`
	ReceiveOrderIncludeToOrderID                      string `json:"receive_order_include_to_order_id"`
	ReceiveOrderInvoiceID                             string `json:"receive_order_invoice_id"`
	ReceiveOrderInvoiceName                           string `json:"receive_order_invoice_name"`
	ReceiveOrderLabelPrintDate                        string `json:"receive_order_label_print_date"`
	ReceiveOrderLabelPrintFlag                        string `json:"receive_order_label_print_flag"`
	ReceiveOrderLastModifiedByID                      string `json:"receive_order_last_modified_by_id"`
	ReceiveOrderLastModifiedByName                    string `json:"receive_order_last_modified_by_name"`
	ReceiveOrderLastModifiedByNullSafeID              string `json:"receive_order_last_modified_by_null_safe_id"`
	ReceiveOrderLastModifiedByNullSafeName            string `json:"receive_order_last_modified_by_null_safe_name"`
	ReceiveOrderLastModifiedDate                      string `json:"receive_order_last_modified_date"`
	ReceiveOrderLastModifiedNullSafeDate              string `json:"receive_order_last_modified_null_safe_date"`
	ReceiveOrderMultiDeliveryParentFlag               string `json:"receive_order_multi_delivery_parent_flag"`
	ReceiveOrderMultiDeliveryParentOrderID            string `json:"receive_order_multi_delivery_parent_order_id"`
	ReceiveOrderNote                                  string `json:"receive_order_note"`
	ReceiveOrderOrderStatusID                         string `json:"receive_order_order_status_id"`
	ReceiveOrderOrderStatusName                       string `json:"receive_order_order_status_name"`
	ReceiveOrderOtherAmount                           string `json:"receive_order_other_amount"`
	ReceiveOrderPaymentMethodID                       string `json:"receive_order_payment_method_id"`
	ReceiveOrderPaymentMethodName                     string `json:"receive_order_payment_method_name"`
	ReceiveOrderPicID                                 string `json:"receive_order_pic_id"`
	ReceiveOrderPicName                               string `json:"receive_order_pic_name"`
	ReceiveOrderPickingInstruct                       string `json:"receive_order_picking_instruct"`
	ReceiveOrderPointAmount                           string `json:"receive_order_point_amount"`
	ReceiveOrderPurchaserAddress1                     string `json:"receive_order_purchaser_address1"`
	ReceiveOrderPurchaserAddress2                     string `json:"receive_order_purchaser_address2"`
	ReceiveOrderPurchaserFax                          string `json:"receive_order_purchaser_fax"`
	ReceiveOrderPurchaserKana                         string `json:"receive_order_purchaser_kana"`
	ReceiveOrderPurchaserMailAddress                  string `json:"receive_order_purchaser_mail_address"`
	ReceiveOrderPurchaserName                         string `json:"receive_order_purchaser_name"`
	ReceiveOrderPurchaserTel                          string `json:"receive_order_purchaser_tel"`
	ReceiveOrderPurchaserZipCode                      string `json:"receive_order_purchaser_zip_code"`
	ReceiveOrderReminderCount                         string `json:"receive_order_reminder_count"`
	ReceiveOrderReminderLastDate                      string `json:"receive_order_reminder_last_date"`
	ReceiveOrderReminderStartDate                     string `json:"receive_order_reminder_start_date"`
	ReceiveOrderSeal1ID                               string `json:"receive_order_seal1_id"`
	ReceiveOrderSeal1Name                             string `json:"receive_order_seal1_name"`
	ReceiveOrderSeal2ID                               string `json:"receive_order_seal2_id"`
	ReceiveOrderSeal2Name                             string `json:"receive_order_seal2_name"`
	ReceiveOrderSeal3ID                               string `json:"receive_order_seal3_id"`
	ReceiveOrderSeal3Name                             string `json:"receive_order_seal3_name"`
	ReceiveOrderSeal4ID                               string `json:"receive_order_seal4_id"`
	ReceiveOrderSeal4Name                             string `json:"receive_order_seal4_name"`
	ReceiveOrderSendDate                              string `json:"receive_order_send_date"`
	ReceiveOrderSendPicID                             string `json:"receive_order_send_pic_id"`
	ReceiveOrderSendPicName                           string `json:"receive_order_send_pic_name"`
	ReceiveOrderSendPlanDate                          string `json:"receive_order_send_plan_date"`
	ReceiveOrderSendSequence                          string `json:"receive_order_send_sequence"`
	ReceiveOrderShopCutFormID                         string `json:"receive_order_shop_cut_form_id"`
	ReceiveOrderShopID                                string `json:"receive_order_shop_id"`
	ReceiveOrderStatementDeliveryInstructPrintingDate string `json:"receive_order_statement_delivery_instruct_printing_date"`
	ReceiveOrderStatementDeliveryPrintingDate         string `json:"receive_order_statement_delivery_printing_date"`
	ReceiveOrderStatementDeliveryText                 string `json:"receive_order_statement_delivery_text"`
	ReceiveOrderTaxAmount                             string `json:"receive_order_tax_amount"`
	ReceiveOrderTemperatureID                         string `json:"receive_order_temperature_id"`
	ReceiveOrderTemperatureName                       string `json:"receive_order_temperature_name"`
	ReceiveOrderTotalAmount                           string `json:"receive_order_total_amount"`
	ReceiveOrderWorkerText                            string `json:"receive_order_worker_text"`
}
